# Generated by Django 4.2.7 on 2024-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gallery_options_alter_gallery_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='details',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='images/gallery'),
        ),
    ]
