# Generated by Django 4.2.7 on 2024-04-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gallery_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/home_screen_images/')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
