# Generated by Django 4.2.7 on 2024-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_homescreenimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('project_info', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homescreenimages',
            options={'verbose_name_plural': 'Home Screen Images'},
        ),
    ]
