# Generated by Django 4.2.7 on 2024-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_projectinprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinprogress',
            options={'verbose_name_plural': 'Projects in Progress'},
        ),
        migrations.AlterField(
            model_name='projectinprogress',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
