# Generated by Django 4.2.7 on 2024-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_projectinprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinprogress',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
